spring.application.name=perfulandia
spring.datasource.url=jdbc:postgresql://dpg-d1gsvijipnbc73b5fsmg-a.virginia-postgres.render.com:5432/perfulandiadb
spring.datasource.username=perfulandiadb_user
spring.datasource.password=57XvaurvsAmy2xClsUJ7slTf07ALBjQv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html